export default {
    SET_SERVER_RESPONSE_ERROR: "SET_SERVER_RESPONSE_ERROR",
    SET_ASSIGNMENTS: "SET_ASSIGNMENTS",
    SET_ASSIGNMENT: "SET_ASSIGNMENT",
    ADD_ASSIGNMENT: "ADD_ASSIGNMENT",
    EDIT_ASSIGNMENT: "EDIT_ASSIGNMENT",
    REMOVE_ASSIGNMENT: "REMOVE_ASSIGNMENT",
    TOGGLE_MODAL: "TOGGLE_MODAL",
};
