export default {
    SET_SERVER_RESPONSE_ERROR: "SET_SERVER_RESPONSE_ERROR",
    CLEAR_SERVER_RESPONSE_ERROR: "CLEAR_SERVER_RESPONSE_ERROR",
    SET_USER: "SET_USER",
    SET_TOKEN: "SET_TOKEN",
    LOGOUT_USER: "LOGOUT_USER",
    TOGGLE_SENDING_MODE: "TOGGLE_SENDING_MODE",
};
